import uuid
import json
import time
import zipfile
import os
import fitz
from typing import List, Dict

def rms_and_pdfs_paths_to_zip(
    pages_paths: List[Dict[str, str]], 
    output_zip_path: str, 
    visible_name: str = "Converted Document"
) -> str:
    """
    Combines individual page PDFs into one master PDF and packages them 
    with their corresponding .rm stroke files into a reMarkable .zip.
    """
    doc_uuid = str(uuid.uuid4())
    timestamp = str(int(time.time() * 1000))
    
    # 1. Merge all individual page PDFs into one master document
    master_pdf_doc = fitz.open()
    page_uuids = []
    
    for entry in pages_paths:
        # Load the single-page PDF generated by the PDF engine
        page_pdf = fitz.open(entry['page_PDF_path'])
        master_pdf_doc.insert_pdf(page_pdf)
        page_pdf.close()
        
        # Generate a unique ID for this specific page's strokes
        page_uuids.append(str(uuid.uuid4()))

    # Save merged PDF to a bytes object for zipping
    master_pdf_bytes = master_pdf_doc.tobytes()
    master_pdf_doc.close()

    # 2. Construct Document Metadata (.metadata)
    doc_metadata = {
        "deleted": False,
        "lastModified": timestamp,
        "metadatamodified": False,
        "modified": False,
        "parent": "",
        "pinned": False,
        "synced": False,
        "type": "DocumentType",
        "version": 1,
        "visibleName": visible_name
    }

    # 3. Construct Document Content (.content)
    doc_content = {
        "extraMetadata": {},
        "fileType": "pdf",
        "pageCount": len(pages_paths),
        "pages": page_uuids,
        "orientation": "portrait",
        "customZoomOrientation": "portrait",
        "transform": {}
    }

    # 4. Create the ZIP archive
    with zipfile.ZipFile(output_zip_path, 'w', zipfile.ZIP_DEFLATED) as rm_zip:
        # Write the master PDF and document-level metadata
        rm_zip.writestr(f"{doc_uuid}.pdf", master_pdf_bytes)
        rm_zip.writestr(f"{doc_uuid}.metadata", json.dumps(doc_metadata, indent=4))
        rm_zip.writestr(f"{doc_uuid}.content", json.dumps(doc_content, indent=4))

        # Write the individual .rm files and their metadata for each page
        for i, entry in enumerate(pages_paths):
            p_uuid = page_uuids[i]
            
            # Read the .rm file generated by the RM engine
            with open(entry['page_RM_path'], 'rb') as f:
                rm_data = f.read()
            
            # Individual page layer metadata
            page_metadata = {"layers": [{"name": "Layer 1"}]}

            # Place in the {uuid}/ folder structure
            rm_zip.writestr(f"{doc_uuid}/{p_uuid}.rm", rm_data)
            rm_zip.writestr(f"{doc_uuid}/{p_uuid}-metadata.json", json.dumps(page_metadata, indent=4))

    return output_zip_path
